// ─── Git Authentication via GIT_ASKPASS ───
// Provides per-operation token injection for git commands.
// Tokens are NEVER embedded in URLs or persisted to .git/config.
// Uses GIT_ASKPASS + env var pattern for secure credential passing.

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { execSync, exec, type ExecSyncOptions } from 'child_process';
import { getEnvWithFallback } from './config.js';

/**
 * Create a temporary GIT_ASKPASS script that echoes a token.
 * The script reads the token from the GIT_AUTH_TOKEN env var (set per-invocation).
 * Returns the path to the script (caller must clean up).
 */
export function createAskPassScript(): string {
  const scriptPath = path.join(
    os.tmpdir(),
    `git-askpass-${process.pid}-${Date.now()}.sh`,
  );
  // The script echoes the token from env — never from disk
  fs.writeFileSync(scriptPath, '#!/bin/sh\necho "$GIT_AUTH_TOKEN"\n', {
    mode: 0o700,
  });
  return scriptPath;
}

/**
 * Build the environment object for authenticated git operations.
 * Uses a credential helper script that echoes protocol/host/username/password
 * to git's credential subsystem. This works for bare clones and all git operations.
 */
function buildGitAuthEnv(
  token: string,
  askPassScript: string,
): Record<string, string | undefined> {
  return {
    ...process.env,
    GIT_TERMINAL_PROMPT: '0',
    GIT_ASKPASS: askPassScript,
    GIT_AUTH_TOKEN: token,
    // Use a credential helper that provides the token
    GIT_CONFIG_NOSYSTEM: '1',
    GIT_CONFIG_COUNT: '1',
    GIT_CONFIG_KEY_0: 'credential.helper',
    GIT_CONFIG_VALUE_0: `!f() { echo "username=x-token"; echo "password=$GIT_AUTH_TOKEN"; }; f`,
  };
}

/**
 * Run a git command synchronously with per-operation token injection via GIT_ASKPASS.
 * Token is passed via environment variable, never via URL or disk.
 */
export function runGitWithToken(
  cmd: string,
  token: string,
  cwd?: string,
  askPassScript?: string,
): string {
  const ownScript = !askPassScript;
  const script = askPassScript || createAskPassScript();
  try {
    return execSync(cmd, {
      cwd,
      encoding: 'utf-8',
      timeout: 120_000,
      env: buildGitAuthEnv(token, script),
    }).trim();
  } finally {
    if (ownScript) {
      try {
        fs.unlinkSync(script);
      } catch {
        /* cleanup best-effort */
      }
    }
  }
}

/**
 * Run a git command asynchronously with per-operation token injection via GIT_ASKPASS.
 */
export function runGitWithTokenAsync(
  cmd: string,
  token: string,
  cwd?: string,
  askPassScript?: string,
): Promise<string> {
  const ownScript = !askPassScript;
  const script = askPassScript || createAskPassScript();
  return new Promise((resolve, reject) => {
    exec(
      cmd,
      {
        cwd,
        encoding: 'utf-8',
        timeout: 120_000,
        env: buildGitAuthEnv(token, script),
      },
      (error, stdout, stderr) => {
        if (ownScript) {
          try {
            fs.unlinkSync(script);
          } catch {
            /* cleanup best-effort */
          }
        }
        if (error) {
          reject(new Error(`${error.message}\n${stderr}`));
        } else {
          resolve(stdout.trim());
        }
      },
    );
  });
}

/**
 * Sanitize a URL by removing any embedded credentials.
 * Use before logging or storing URLs — NEVER log raw repo URLs.
 */
export function sanitizeGitUrl(url: string): string {
  try {
    const parsed = new URL(url);
    if (parsed.username || parsed.password) {
      parsed.username = '';
      parsed.password = '';
    }
    return parsed.toString();
  } catch {
    // Not a valid URL, return as-is but mask potential tokens
    return url.replace(/\/\/[^@]+@/, '//***@');
  }
}

/**
 * Configure git credential helper inside a worktree so the agent container
 * can push/pull using per-workspace GitHub tokens resolved from Delegate API.
 *
 * Writes a credential-helper script that calls the Delegate token endpoint
 * and configures the worktree's local git config to use it.
 */
export function configureWorktreeGitAuth(
  worktreePath: string,
  workspaceId: string,
): void {
  const DELEGATE_URL = process.env.DELEGATE_URL || 'https://delegate.ws';
  // Canonical: DELEGATE_AGENT_TOKEN. Legacy fallback: DELEGATE_API_KEY.
  const DELEGATE_AGENT_TOKEN =
    getEnvWithFallback('DELEGATE_AGENT_TOKEN', ['DELEGATE_API_KEY']) || '';

  if (!DELEGATE_AGENT_TOKEN) return;

  // Write a credential helper script that resolves tokens from Delegate API
  // The script runs inside the container where worktreePath is at /workspace/group/workspace/
  const helperScript = `#!/bin/sh
# Git credential helper — resolves per-workspace GitHub tokens from Delegate API
# Auto-generated by DelegateAgent for workspace ${workspaceId}
TOKEN=$(curl -sf -m 5 \\
  -H "Authorization: Bearer ${DELEGATE_AGENT_TOKEN}" \\
  "${DELEGATE_URL}/api/agent/integrations/token?provider=github&workspaceId=${workspaceId}" \\
  | grep -o '"token":"[^"]*"' | cut -d'"' -f4)

if [ -z "$TOKEN" ]; then
  exit 1
fi

echo "protocol=https"
echo "host=github.com"
echo "username=x-token"
echo "password=$TOKEN"
`;

  const helperPath = path.join(worktreePath, '.git-credential-helper.sh');
  fs.writeFileSync(helperPath, helperScript, { mode: 0o755 }); // world-executable for container user

  // Configure local git to use this credential helper
  // Use a relative path so it works both on host and inside container
  // (host: /opt/delegate-agent/groups/{folder}/workspace/, container: /workspace/group/workspace/)
  try {
    execSync(
      `git config --local credential.helper "/workspace/group/workspace/.git-credential-helper.sh"`,
      {
        cwd: worktreePath,
        encoding: 'utf-8',
        timeout: 5000,
        env: { ...process.env, GIT_TERMINAL_PROMPT: '0' },
      },
    );

    // Set user for commits
    execSync(`git config --local user.email "agent@delegate.ws"`, {
      cwd: worktreePath,
      encoding: 'utf-8',
      timeout: 5000,
    });
    execSync(`git config --local user.name "Delegate Agent"`, {
      cwd: worktreePath,
      encoding: 'utf-8',
      timeout: 5000,
    });

    // Write a .gitconfig for the container user (node, uid 1000)
    // so safe.directory is set when the container mounts this worktree
    const sessionsDir =
      process.env.SESSIONS_DIR || '/opt/delegate-agent/data/sessions';
    const sessionGitconfig = path.join(
      sessionsDir,
      path.basename(path.dirname(worktreePath)),
      '.gitconfig',
    );
    fs.mkdirSync(path.dirname(sessionGitconfig), { recursive: true });
    fs.writeFileSync(sessionGitconfig, '[safe]\n\tdirectory = *\n');
  } catch {
    // Non-fatal
  }
}

/**
 * Sanitize legacy bare clones that have embedded tokens in remote URLs.
 * Replaces the remote origin URL with a clean (credential-free) version.
 * Non-fatal — bare clone is still usable even if sanitization fails.
 */
export function sanitizeBareCloneRemote(
  bareDir: string,
  cleanUrl: string,
): void {
  try {
    execSync(`git remote set-url origin "${cleanUrl}"`, {
      cwd: bareDir,
      encoding: 'utf-8',
      timeout: 10_000,
      env: { ...process.env, GIT_TERMINAL_PROMPT: '0' },
    });
  } catch {
    // Non-fatal — bare clone still usable
  }
}
